# --------------------------------------------
# Configuração geral do site Jekyll - MPG Tech
# --------------------------------------------

title: "MPG Tech"
email: mauricio.mpgtech@gmail.com
description: >-
  Site da MPG Tech — inovações sustentáveis e tecnologia têxtil.
  Desenvolvimento e pesquisa em tingimento com IA e processos ecológicos.

# Caminhos base (IMPORTANTE para GitHub Pages)
url: "https://mauriciojosefowicz.github.io"   # domínio principal SEM / no final
baseurl: "/mpgtech"                           # nome do repositório GitHub

twitter_username: mpgtech
github_username:  mauriciojosefowicz

# --------------------------------------------
# Build e plugins
# --------------------------------------------
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# --------------------------------------------
# Exclusões (não enviar para o build)
# --------------------------------------------
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE

force_rebuild: 6
